#!/usr/bin/env node
// Copyright 2026 Cloudsmith Ltd

import { readdir, readFile, writeFile, mkdir } from 'fs/promises';
import { join, relative, basename } from 'path';
import { fileURLToPath } from 'url';
import { dirname } from 'path';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const rootDir = join(__dirname, '..');
const distDir = join(rootDir, 'dist');

/**
 * Recursively find all .rego files in a directory
 * @param {string} dir - Directory to search
 * @param {string} baseDir - Base directory for relative paths
 * @returns {Promise<Array<{absolutePath: string, relativePath: string, name: string}>>}
 */
async function findRegoFiles(dir, baseDir = dir) {
  const entries = await readdir(dir, { withFileTypes: true });
  const files = [];

  for (const entry of entries) {
    const fullPath = join(dir, entry.name);

    if (entry.isDirectory()) {
      const subFiles = await findRegoFiles(fullPath, baseDir);
      files.push(...subFiles);
    } else if (entry.isFile() && entry.name.endsWith('.rego')) {
      const relativePath = relative(baseDir, fullPath);
      files.push({
        absolutePath: fullPath,
        relativePath,
        name: basename(entry.name, '.rego'),
      });
    }
  }

  return files;
}

/**
 * Convert a file path to a safe JavaScript identifier
 * Uses the full path to ensure uniqueness (e.g., legacy/recipe-1/policy.rego -> legacyRecipe1Policy)
 * @param {string} path - File path to convert (e.g., "baseline/cooldown.rego")
 * @returns {string}
 */
function toSafeIdentifier(path) {
  // Remove .rego extension and convert path separators, hyphens, underscores to camelCase
  return path
    .replace(/\.rego$/, '') // Remove .rego extension
    .replace(/[\/\-_]([a-z])/g, (_, char) => char.toUpperCase()) // Convert separators to camelCase
    .replace(/^([a-z])/, (_, char) => char.toLowerCase()) // Ensure first char is lowercase
    .replace(/[^a-zA-Z0-9]/g, ''); // Remove any remaining special chars
}

/**
 * Escape string content for use in JavaScript template literals
 * @param {string} content - Content to escape
 * @returns {string}
 */
function escapeTemplateString(content) {
  return content
    .replace(/\\/g, '\\\\') // Escape backslashes
    .replace(/`/g, '\\`') // Escape backticks
    .replace(/\$/g, '\\$'); // Escape dollar signs
}

/**
 * Generate the main index.js module
 * @param {Array<{absolutePath: string, relativePath: string, name: string}>} policies
 * @returns {Promise<void>}
 */
async function generateIndexJs(policies) {
  const contentDeclarations = [];
  const exports = [];

  for (const policy of policies) {
    const identifier = toSafeIdentifier(policy.relativePath);

    // Read the .rego file content and inline it
    const regoContent = await readFile(policy.absolutePath, 'utf-8');
    const escapedContent = escapeTemplateString(regoContent);

    contentDeclarations.push(
      `const ${identifier}Content = \`${escapedContent}\`;`,
    );

    exports.push(
      `export const ${identifier} = {
  name: '${policy.name}',
  path: '${policy.relativePath}',
  content: ${identifier}Content,
};`,
    );
  }

  const content = `// Copyright 2026 Cloudsmith Ltd
// Auto-generated by scripts/build.js - DO NOT EDIT

${contentDeclarations.join('\n\n')}

${exports.join('\n\n')}

// Export all policies as a collection
export const allPolicies = [
  ${policies.map((p) => toSafeIdentifier(p.relativePath)).join(',\n  ')},
];
`;

  await writeFile(join(distDir, 'index.js'), content, 'utf-8');
}

/**
 * Generate the index.d.ts TypeScript definitions
 * @param {Array<{absolutePath: string, relativePath: string, name: string}>} policies
 * @returns {Promise<void>}
 */
async function generateIndexDts(policies) {
  const interfaces = [];
  const exports = [];

  const policyInterface = `export interface Policy {
  /** The policy name (filename without .rego extension) */
  name: string;
  /** Relative path to the .rego file from package root */
  path: string;
  /** The raw .rego file content as a string */
  content: string;
}`;

  for (const policy of policies) {
    const identifier = toSafeIdentifier(policy.relativePath);
    exports.push(`export const ${identifier}: Policy;`);
  }

  const content = `// Copyright 2026 Cloudsmith Ltd
// Auto-generated by scripts/build.js - DO NOT EDIT

${policyInterface}

${exports.join('\n')}

/** All policies as a collection */
export const allPolicies: Policy[];
`;

  await writeFile(join(distDir, 'index.d.ts'), content, 'utf-8');
}

/**
 * Main build function
 */
async function build() {
  console.log('Building @cloudsmith/rego-recipes...\n');

  // Ensure dist directory exists
  await mkdir(distDir, { recursive: true });

  // Directories to scan for .rego files
  const policyDirs = ['baseline', 'advanced', 'legacy'];

  // Find all .rego files in each directory
  /** @type {Record<string, Array<{absolutePath: string, relativePath: string, name: string}>>} */
  const policiesByDir = {};
  for (const dir of policyDirs) {
    policiesByDir[dir] = await findRegoFiles(join(rootDir, dir), rootDir);
  }

  const allPolicies = Object.values(policiesByDir).flat();

  console.log(`Found ${allPolicies.length} policy files:`);
  for (const dir of policyDirs) {
    console.log(`  - ${policiesByDir[dir].length} from ${dir}/`);
  }
  console.log('');

  // Generate output files
  console.log('Generating dist/index.js...');
  await generateIndexJs(allPolicies);

  console.log('Generating dist/index.d.ts...');
  await generateIndexDts(allPolicies);

  console.log('\n✓ Build complete!\n');

  // List exported policy names
  console.log('Exported policies:');
  for (const policy of allPolicies) {
    const identifier = toSafeIdentifier(policy.relativePath);
    console.log(`  - ${identifier} (${policy.relativePath})`);
  }
}

// Run build
build().catch((error) => {
  console.error('Build failed:', error);
  process.exit(1);
});
