name: OPA Lint & Validate

on:
  pull_request:
  push:
    branches: [main]

jobs:
  opa:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install OPA
        run: |
          curl -L -o opa https://openpolicyagent.org/downloads/latest/opa_linux_amd64_static
          chmod +x opa
          sudo mv opa /usr/local/bin/

      - name: Show OPA Version
        run: opa version
      - name: Install Regal
        run: |
          curl -L -o regal https://github.com/StyraInc/regal/releases/latest/download/regal_Linux_x86_64
          chmod +x regal
          sudo mv regal /usr/local/bin/regal

      - name: Lint with Regal
        run: regal lint baseline advanced
      - name: Format Check
        run: |
          if [ -d baseline ]; then
            opa fmt --fail baseline
          else
            echo "No baseline folder"
          fi
          if [ -d advanced ]; then
            opa fmt --fail advanced
          else
            echo "No advanced folder"
          fi

      - name: Validate Policies
        run: |
          find baseline advanced -name "*.rego" -print0 | \
          while IFS= read -r -d '' file; do
            echo "Checking $file"
            opa check "$file"
          done

      - name: Unit Test Policies
        run: |
          find baseline advanced -name "*_test.rego" -print0 | \
          while IFS= read -r -d '' test_file; do
            policy="${test_file/_test/}"
            echo "Testing $test_file"
            opa test "$policy" "$test_file"
          done

